name: Flask Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/citrusi_2fa:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/citrusi_2fa:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/citrusi_2fa:${{ github.sha }}
          docker stop citrusi_2fa || true
          docker rm citrusi_2fa || true
          docker run --name flask_app -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/citrusi_2fa:${{ github.sha }}

